language: node_js
node_js:
  - 16
install:
  - npm install
  - cd lib && npm ci && cd ..
  - cd lib-testing && npm ci && cd ..
  - cd client && npm ci && cd ..
script:
  - npm run format:check
  - npm run lint:check
  - cd client && npm run check && npm run build && cd ..
  - cd lib && npm run build && cd ..
  - npm test