export const BritishCities = [
  'Aberdeen',
  'Bath',
  'Birmingham',
  'Belfast',
  'Bristol',
  'Cambridge',
  'Cardiff',
  'Edinburgh',
  'Exeter',
  'Glasgow',
  'Gloucester',
  'Lancaster',
  'Leicester',
  'Lincoln',
  'Liverpool',
  'London',
  'Manchester',
  'Norwich',
  'Nottingham',
  'Oxford',
  'Plymouth',
  'Portsmouth',
  'Preston',
  'St Albans',
  'Salisbury',
  'Sheffield',
  'Southampton',
  'Swansea',
  'Westminster',
  'Winchester',
  'Wolverhampton',
  'Worcester',
  'York'
]

const CountriesInEurope = [
  { name: 'Albania', code: 'AL', capital: 'Tirana' },
  { name: 'Austria', code: 'AT', capital: 'Vienna' },
  { name: 'Belarus', code: 'BY', capital: 'Minsk' },
  { name: 'Belgium', code: 'BE', capital: 'Brussels' },
  { name: 'Bosnia and Herzegovina', code: 'BA', capital: 'Sarajevo' },
  { name: 'Bulgaria', code: 'BG', capital: 'Sofia' },
  { name: 'Croatia', code: 'HR', capital: 'Zagreb' },
  { name: 'Czech Republic', code: 'CZ', capital: 'Prague' },
  { name: 'Denmark', code: 'DK', capital: 'Copenhagen' },
  { name: 'Estonia', code: 'EE', capital: 'Tallinn' },
  { name: 'Finland', code: 'FI', capital: 'Helsinki' },
  { name: 'France', code: 'FR', capital: 'Paris' },
  { name: 'Germany', code: 'DE', capital: 'Berlin' },
  { name: 'Greece', code: 'GR', capital: 'Athens' },
  { name: 'Hungary', code: 'HU', capital: 'Budapest' },
  { name: 'Iceland', code: 'IS', capital: 'Reykjavik' },
  { name: 'Ireland', code: 'IE', capital: 'Dublin' },
  { name: 'Isle of Man', code: 'IM', capital: 'Douglas, Isle of Man' },
  { name: 'Italy', code: 'IT', capital: 'Rome' },
  { name: 'Jersey', code: 'JE', capital: 'Saint Helier' },
  { name: 'Kosovo', code: 'XK', capital: 'Pristina' },
  { name: 'Latvia', code: 'LV', capital: 'Riga' },
  { name: 'Liechtenstein', code: 'LI', capital: 'Vaduz' },
  { name: 'Lithuania', code: 'LT', capital: 'Vilnius' },
  { name: 'Luxembourg', code: 'LU', capital: 'Luxembourg' },
  { name: 'Malta', code: 'MT', capital: 'Valletta' },
  { name: 'Moldova, Republic of', code: 'MD', capital: 'Chisinau' },
  { name: 'Monaco', code: 'MC', capital: 'Monaco' },
  { name: 'Montenegro', code: 'ME', capital: 'Podgorica' },
  { name: 'Netherlands', code: 'NL', capital: 'Amsterdam' },
  { name: 'Norway', code: 'NO', capital: 'Oslo' },
  { name: 'Poland', code: 'PL', capital: 'Warsaw' },
  { name: 'Portugal', code: 'PT', capital: 'Lisbon' },
  { name: 'Romania', code: 'RO', capital: 'Bucharest' },
  { name: 'San Marino', code: 'SM', capital: 'San Marino' },
  { name: 'Serbia', code: 'RS', capital: 'Belgrade' },
  { name: 'Slovakia', code: 'SK', capital: 'Bratislava' },
  { name: 'Slovenia', code: 'SI', capital: 'Ljubljana' },
  { name: 'Spain', code: 'ES', capital: 'Madrid' },
  { name: 'Sweden', code: 'SE', capital: 'Stockholm' },
  { name: 'Switzerland', code: 'CH', capital: 'Berne' },
  { name: 'Ukraine', code: 'UA', capital: 'Kiev' },
  { name: 'United Kingdom', code: 'GB', capital: 'London' }
]
